name: Build Android APK

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Allows you to click "Run" manually in GitHub UI

permissions:
  contents: write

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[build]') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Decode Google Services JSON
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Make Gradle executable
        run: chmod +x android/gradlew

      # We create an Environment Variable so we can use it in later steps
      # Result Example: PostHeart-a1b2c3d.apk
      - name: Set APK Name
        run: echo "APK_NAME=PostHeart-${{ github.sha }}.apk" >> $GITHUB_ENV

      - name: Build Release APK
        working-directory: android
        run: ./gradlew assembleRelease -PcustomName=${{ env.APK_NAME }} --build-cache --parallel --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PostHeart-APK
          path: android/app/build/outputs/apk/release/${{ env.APK_NAME }}
          retention-days: 7

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          groups: testers
          file: android/app/build/outputs/apk/release/${{ env.APK_NAME }}
          releaseNotes: ${{ github.event.head_commit.message }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "android/app/build/outputs/apk/release/${{ env.APK_NAME }}"
          tag: "v1.0.${{ github.run_number }}"
          name: "Release ${{ github.run_number }}: ${{ env.APK_NAME }}"
          body: "${{ github.event.head_commit.message }}"
          token: ${{ secrets.GITHUB_TOKEN }}
